name: Docker Image CI POI

on:
  push:
    paths:
      - 'apis/trips/*'
      - '.github/workflows/trips.yml'

jobs:
  build:
    name: Build trips folder
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set Short SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Check SHA
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Try Some Stuff
      run: |
        echo ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openhackebmacr.azurecr.io/devopsoh/api-trips:${{ steps.vars.outputs.sha_short }}
      working-directory: ./apis/trips

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackebmacr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push to ACR
      run: |
        docker push openhackebmacr.azurecr.io/devopsoh/api-trips:${{ steps.vars.outputs.sha_short }}

    - uses: nashmaniac/create-issue-action@v1.1
      name: Create Issue Action
      if: failure()
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: worflow-failed
        body: Workflow failed for commit ${{github.sha}}

