name: Docker Image CI POI

on:
  pull_request:
    paths:
      - 'apis/trips/*'
  pull_request_target:
    types: [opened]
  push:
    paths:
      - 'apis/trips/*'
      - '.github/workflows/trips.yml'

jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Look around
      run: |
        ls -la
        pwd
        echo $GITHUB_SHA
        git log -n 2
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA

    - name: check modified files
      id: check_files
      run: |
        echo "=============== list modified files ==============="
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA 

        echo "========== check paths of modified files =========="
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA > files.txt
        cat files.txt
        while IFS= read -r file
        do
          echo $file
          if [[ $file != apis/trips/* ]]; then
            echo "This modified file is not under the 'api/trips' folder."
            echo "::set-output name=run_job::false"
            break
          else
            echo "::set-output name=run_job::true"
          fi
        done < files.txt

  build:
    name: Build trips folder
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Look around
      run: |
        ls -la
        pwd
        echo "GITHUB_SHA=$GITHUB_SHA"
        echo "GITHUB_REF=$GITHUB_REF"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openhackebmacr.azurecr.io/my-image-name:0.1
      working-directory: ./apis/trips

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackebmacr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push to ACR
      run: |
        docker push openhackebmacr.azurecr.io/my-image-name:0.1
