name: Docker Image CI POI

on:
  push:
    paths:
      - 'apis/trips/*'
      - '.github/workflows/trips.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: trips

    - name: Look around
      run: |
        ls -la trips
        pwd

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      working-directory: ./trips
