name: Docker Image CI POI

on:
  push:
    paths:
      - 'apis/trips/*'
      - '.github/workflows/trips.yml'

jobs:
  build:
    name: Build trips folder
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openhackebmacr.azurecr.io/my-image-name:0.1
      working-directory: ./apis/trips

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackebmacr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push to ACR
      run: |
        docker push openhackebmacr.azurecr.io/my-image-name:0.1
