name: Docker Image CI POI

on:
  pull_request_target:
    types: [opened]

jobs:
  check:
    name: Check changed files
    outputs:
      run_job: ${{ steps.check_files.outputs.run_job }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Look around
      run: |
        ls -la
        pwd
        echo "GITHUB_SHA=$GITHUB_SHA"
        echo "GITHUB_REF=$GITHUB_REF"

- id: check_files
  run: |
    URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
    curl -s -X GET -G $URL | jq -r '.[] | .filename' > files.txt
    cat files.txt
    while IFS= read -r file
    do
      echo $file
      if [[ $file != apis/trips/* ]]; then
        echo "This modified file is not under the 'api/trips' folder."
        echo "::set-output name=run_job::false"
        break
      else
        echo "This modifield file is under 'api/trips' and should trigger a build."
        echo "::set-output name=run_job::true"
      fi
    done < files.txt

  build:
    name: Build trips folder
    needs: check
    if: needs.check.outputs.run_job == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openhackebmacr.azurecr.io/my-image-name:0.1
      working-directory: ./apis/trips

    - name: Login to ACR
      uses: docker/login-action@v1
      with:
        registry: openhackebmacr.azurecr.io
        username: ${{ secrets.AZURE_CLIENT_ID }}
        password: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Push to ACR
      run: |
        docker push openhackebmacr.azurecr.io/my-image-name:0.1
